name: "Test"

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # no shallow
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - name: traditional nix-build succeeds
      run: nix-build
    - name: flake build + tests
      run: nix flake check --print-build-logs
